### ISSUE TITLE
Cannot query statistics / perfdata from livestatus

### ISSUE THREAD

**Issue by DaveOHenry** [ImmobilienScout24/livestatus_service#3]
When querying statistics like in the following example:
```
http://myserver:8080/query?q=GET%20services%5CnFilter:%20description%20~%20CPU%5CnFilter:%20host_name%20~%20somehost%5CnAnd:%202%5CnStats:%20avg%20perf_data
```
... the livestatus_service returns an error:
```
Error : Cannot format answer [[u'avg=2.57859540 cpu_core_util_0=3.38205640 cpu_core_util_1=3.30645160 user=1.97832660 util=3.34425420']], either the column definitions or the contents are missing
```

To make it work i was thinking of a dirty hack like just returning eval(raw_data) or something, but I failed to find the right spot in the code. Even better would be to somehow parse the string and return valid json, but I think my Python skills are too limited.

Tested with Check_MK 1.2.8b9 on Debian 7.11

**Comment by mriehl** [comment]
Thanks for reporting. Using `Stats` has not been considered up to now.

A possibility is to have `format_answer` parse the response instead of giving up when it does not find the column names. If it's a `[key=value]+` style pattern, then simply use the left hand side terms as column names.

I'll try to look into this but I don't have a system to test this locally currently, so might take some time :-/

**Comment by DaveOHenry** [comment]
Thanks for the reply. I'll be glad to test if that helps. According to https://mathias-kettner.de/checkmk_livestatus.html the pattern is something like...

_GET services
Filter: description ~ CPU util
Stats: avg perf_data_
```
system=6.02900000 user=7.26400000 wait=0.90650000
```
This is the basic case where only one line is returned, but the "Stats:" header may also be used more than once to calculate things like sum, min, max and so on. In that case more than one row is returned which may complicate things.

Parsing sounds like a good idea, but after digging a little bit into LQL this change may not cover all cases. Look at the following query for example:
http://myhost:8080/query?q=GET%20services%5CnFilter:%20host_name%20~%20myserver-%5CnFilter:%20description%20~%20CPU%5CnAnd:%202%5CnStats:%20avg%20perf_data%5CnStats:%20state%20=%203
This returns the average performance data for CPU-related services and the number of hosts that are in state critical for all hosts matching the filter. 

Output from livestatus_service:
```
Error : Cannot format answer [[u'cpu_core_util_0=0.26606940 cpu_core_util_1=0.30609820 guest=0.00000000 load1=0.00000000 load15=0.05000000 load5=0.01000000 steal=0.00998240 system=0.08320000 user=0.16660000 wait=0.03000000', 0]], either the column definitions or the contents are missing
```

As far as I understand it the value of a "Stats:" header behaves like a single item from the "Column:" header: It is the key for some value(s). Maybe it should be treated as such. Problematic could be that "Stats:" has the same syntax as "Filter:". Therefore it may contain whitespaces and special characters.

**Comment by DaveOHenry** [comment]
Currently testing a quick fix in my environment. Basically parsing the "Stats:" headers inside "determine_columns_to_show_from_query" and setting them as keys for the values. At first glance it seems to work. Need some more testing to be sure everything works.

**Comment by DaveOHenry** [comment]
As far as I can see its working as expected, but the main problem I see is the naming of the json keys, because the "Stats:" header may contain special characters. We could strip these characters, but then there may be duplicate field names that may break json syntax when using something like:
Stats: state > 2
Stats: state = 2

When deleting / replacing the special chars there would be 2 fields named "state_2" for example. This would need further tweaking. 

Currently I have it working without replacing special characters (example):

request
```
http://myhost:8080/query?q=GET%20services%5CnFilter:%20host_name%20~%20myserver%5CnFilter:%20description%20~%20CPU%5CnAnd:%202%5CnStats:%20avg%20perf_data%5CnStats:%20state%20=%203%5CnColumns:%20host_name
```

response:
```
[
 {
  "avg perf_data": "cpu_core_util_0=0.31412700 cpu_core_util_1=0.19839600 guest=0.00000000 load1=0.00000000 load15=0.05000000 load5=0.01000000 steal=0.00826700 system=0.08300000 user=0.15700000 wait=0.01700000",
  "state = 3": 0,
  "host_name": "myserver01"
 },
 {
  "avg perf_data": "cpu_core_util_0=0.18192300 cpu_core_util_1=0.26461600 guest=0.00000000 load1=0.00000000 load15=0.05000000 load5=0.02000000 steal=0.00826900 system=0.08300000 user=0.10800000 wait=0.03300000",
  "state = 3": 0,
  "host_name": "myserver02"
 },
 {
  "avg perf_data": "cpu_core_util_0=0.43057100 cpu_core_util_1=0.34776800 guest=0.00000000 load1=0.00000000 load15=0.05000000 load5=0.01000000 steal=0.00828000 system=0.05000000 user=0.29800000 wait=0.01700000",
  "state = 3": 0,
  "host_name": "myserver03"
 }
]
```

Maybe the query does not make much sense, but at least data is returned. The key names may look strange, but should be valid json in almost any case. The only problematic case I can think of is some weird regexes inside the "Stats:" headers.
Parsing "perf_data" would be the cherry on the cake, but this can also easily be done on client-side.

I'm not familiar with git, but may try to submit a pull request if anyone is interested.

**Comment by mriehl** [comment]
IMHO if it works in some cases it's already better than the current implementation ;-)
I'd merge for sure if you put together a pull request. If you need help along the way feel free to reach out!

**Comment by DaveOHenry** [comment]
Thanks a lot for merging the changes. Your service makes querying livestatus from different systems a lot easier. No hassle with Unix socket and bash stuff needed. Just plain http with real json answers which all of our systems can easily understand out of the box.

As already mentioned in the PR grouping with `StatsAnd` and `StatsOr` may not work as expected, but we are not using these currently. If we ever need this feature I may take a look at possible improvements again.
So I'll close this issue as querying Stats now basically works fine with our current requirements.
